---
- name: Check if v2ray is already installed
  stat:
    path: /usr/local/bin/v2ray
  register: v2ray_executable

- name: Install Red Hat system specific packages
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and (not v2ray_executable.stat.exists|d(False))

- name: Install Debian system specific packages
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian' and (not v2ray_executable.stat.exists|d(False))

- name: Install Arch Linux system specific packages
  include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux' and (not v2ray_executable.stat.exists|d(False))

- name: Install v2ray using official setup script
  become: true
  shell: |
    set -o pipefail
    curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
    bash install-release.sh
  args:
    executable: /bin/bash
    creates: /usr/local/bin/v2ray
    warn: no
  notify:
    - start v2ray
    - enable v2ray

- name: Check, update config.json and restart v2ray
  become: true
  block:
    - name: Make sure config.json has desired content
      template:
        src: "{{ v2ray_config_json_path | default('config.j2') }}"
        dest: /etc/v2ray/config.json
        owner: root
        group: root
        mode: "0644"
      register: config_json
    - name: Check config.json syntax
      command: /usr/local/bin/v2ray -test -config=/etc/v2ray/config.json
      register: check_result
      failed_when: not (check_result.rc == 0)
      when: config_json.changed
      notify:
        - restart v2ray
  when: update_v2ray_config_json
