---
- name: Install system dependencies for {{ ansible_os_family }}
  apt:
    name: curl
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install system dependencies for {{ ansible_os_family }}
  yum:
    name: curl
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install v2ray using official setup script
  shell: |
    set -o pipefail
    curl -Ls https://install.direct/go.sh | sudo bash
  args:
    executable: /bin/bash
    creates: /usr/bin/v2ray/v2ray
    warn: no

- name: Update config.json
  become: true
  template:
    src: "{{ config_json_path | default('config.j2') }}"
    dest: /etc/v2ray/config.json
    owner: root
    group: root
    mode: '0644'
  notify:
  - restart v2ray
