---
- name: Install Red Hat system specific packages
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Debian system specific packages
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Arch Linux system specific packages
  include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Install v2ray using official setup script
  become: true
  shell: |
    set -o pipefail
    curl -Ls https://install.direct/go.sh | sudo bash
  args:
    executable: /bin/bash
    creates: /usr/bin/v2ray/v2ray
    warn: no

- name: Update config.json
  become: true
  template:
    src: "{{ v2ray_config_json_path | default('config.j2') }}"
    dest: /etc/v2ray/config.json
    owner: root
    group: root
    mode: '0644'
  notify:
  - restart v2ray
